# Generated by Django 5.1.1 on 2024-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_email', models.CharField(default='', max_length=100, unique=True)),
                ('user_password', models.CharField(default='', max_length=100)),
                ('user_category', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
