# Generated by Django 5.1.1 on 2024-12-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField()),
                ('cited_by', models.IntegerField()),
                ('co_author', models.TextField()),
                ('conference', models.CharField(blank=True, max_length=255, null=True)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
                ('domains', models.TextField()),
                ('download_links', models.TextField()),
            ],
        ),
    ]
